name: resturant_assigment_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.1.0
  http: ^1.2.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
